apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/saas-health-check: 'true'
    prometheus.io/path: /health_check
  name: {{ template "relicthief.fullname" . }}
  labels:
    app: {{ template "relicthief.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "relicthief.name" . }}
    release: {{ .Release.Name }}
    role: master
